name: Slack Web API Action
description: An action to notify Slack using the chat.postMessage API
author: yukin01
inputs:
  status:
    description: Job results. In most use cases, you should specify `job.status`.
    required: true
  github_token:
    description: Personal access token (PAT) used to fetch the repository.
    required: false
    default: ${{ github.token }}
  oauth_token:
    description: |
      Slack's access token. If you're using modern Slack Apps,
      specify the **Bot User OAuth Access Token** which begin with `xoxb-`.
    required: true
  channel:
    description: The channel to be notified of results.
    required: true
  text:
    description: todo
    required: false
    default: ''
  username:
    description: todo
    required: false
    default: ''
  icon_emoji:
    description: todo
    required: false
    default: ''
  icon_url:
    description: todo
    required: false
    default: ''
runs:
  using: node12
  main: dist/index.js
